# NUMPY

In [ ]:
import numpy as np

# ARRAY

In [2]:
# 1 D
# array
arr = np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [4]:
# dimension
arr.ndim

1

In [5]:
#shape
arr.shape

(3,)

In [6]:
# size
arr.size

3

In [7]:
# data type
arr.dtype

dtype('int32')

In [11]:
# 2 D
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# shape
arr.shape

(2, 3)

In [13]:
# size
arr.size

6

In [14]:
#data type
arr.dtype

dtype('int32')

In [15]:
# dimension
arr.ndim

2

In [16]:
# 3 D
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [17]:
#shape 
arr.shape

(1, 3, 3)

In [18]:
#size
arr.size

9

In [19]:
# data type
arr.dtype

dtype('int32')

In [20]:
#dimension
arr.ndim

3

In [21]:
# use slicing and take 8 outside.
arr[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr[0][2]

array([7, 8, 9])

In [23]:
arr[0][2][1]
# so this the main to take o/p in our array

8

In [24]:
# if we want to change our data 8 to 10....?
arr[0][2][1] = 10

In [25]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, 10,  9]]])

# SOME FUNCTIONS_ _ _

In [26]:
# MAX
# MIN
# SUM
# AXIS

# ONES
# ZEROS
# EMPTY
# LINSPACE
# ARANGE
# TRANSPOSE
# IDENTITY

In [27]:
x = np.array ([[23,90,-4],[67,3,45]])
x

array([[23, 90, -4],
       [67,  3, 45]])

In [29]:
# if want max in this data
x.max()

90

In [30]:
# if want min in this data
x.min()

-4

In [31]:
# if want sum this data
x.sum()

224

In [34]:
# if we want to sum no. in x or y axis then we use axis
# axis = 0(column)    axis =1(row)

# sum the column
x.sum(axis =0) 

array([90, 93, 41])

In [36]:
x.sum(axis =0) .sum()

224

In [37]:
# sum the row
x.sum(axis = 1)

array([109, 115])

In [39]:
x.sum(axis = 1).sum()

224

In [41]:
# ONES
# it gives always vale in 1
 
np.ones(4)

array([1., 1., 1., 1.])

In [42]:
# ZEROS
# it gives 0 values 

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
# EMPTY 
# it gives any random values

np.empty(12)

array([1.02029609e-311, 2.86558075e-322, 0.00000000e+000, 0.00000000e+000,
       2.12199579e-313, 5.74084271e+169, 5.27845992e-091, 1.91755887e-076,
       8.26571662e-072, 1.90227046e+185, 6.48224659e+170, 5.82471487e+257])

In [49]:
# LINSPACE 
# it also give random value but in same difference

np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [50]:
# we can also provide a differnce in between no. as like that.....

np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [53]:
# arange 
# in this function we give a range in between values

np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [54]:
np.arange(2,6)

array([2, 3, 4, 5])

In [58]:
np.arange(2,7,2)

array([2, 4, 6])

In [59]:
np.arange(2,50,4)

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46])

In [60]:
# identity
# this function provide a identity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
# transpose 
# this term convert row in column or column in row

x = np.array([[1,4,7],[89,3,6]])
x

array([[ 1,  4,  7],
       [89,  3,  6]])

In [63]:
x.T

array([[ 1, 89],
       [ 4,  3],
       [ 7,  6]])

In [65]:
# sort
# it converts data in sort form meanns in aassending order

x.sort()
x

array([[ 1,  4,  7],
       [ 3,  6, 89]])

In [66]:
# argmax
# where is the maximum data in our data

x.argmax()

5

In [67]:
# argmax
# where is the minimum data in our data

x.argmin()

0

In [70]:
x.argsort()

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)